const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{createServer}=require('./serve-mobile-check.cjs');
(async()=>{let browser;const server=createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;try{
 const manifest=JSON.parse(fs.readFileSync(path.join(__dirname,'../dist/site.webmanifest'),'utf8'));assert.equal(manifest.name,'Vasu-Devs — AI Engineer');assert.equal(manifest.display,'browser');assert(manifest.icons.some(i=>i.purpose==='maskable'));assert(fs.readFileSync(path.join(__dirname,'../dist/robots.txt'),'utf8').includes('Allow: /'));assert(fs.readFileSync(path.join(__dirname,'../dist/sitemap.xml'),'utf8').includes('<loc>https://www.siddhvasudev.com/</loc>'));
 browser=await chromium.launch();const page=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.abort());await page.goto(base);
 for(const icon of manifest.icons){const dimensions=await page.evaluate(async url=>{const img=new Image();img.src=url;await img.decode();return img.naturalWidth+'x'+img.naturalHeight},base+icon.src);assert.equal(dimensions,icon.sizes)}
 const schema=JSON.parse(await page.locator('script[type="application/ld+json"]').textContent());assert.equal(schema['@graph'][0].name,'Vasudev Siddh');
 await page.locator('.navigation [data-page=projects]').focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>document.title==='Work — Vasu-Devs'&&document.activeElement.matches('#projects h1,#projects h2'));
 await page.locator('.skip').focus();await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>document.activeElement.id),'main');assert(await page.locator('#projects').isVisible(),'Skip link changed section');
 await page.locator('.navigation [data-page=contact]').click();await page.waitForFunction(()=>document.title==='Contact — Vasu-Devs');
 await page.evaluate(()=>{Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async text=>{window.copiedEmail=text}}})});await page.locator('.copy-mail:visible').first().click();assert((await page.locator('.sr-only[role=status]').textContent()).includes('copied'));assert((await page.evaluate(()=>window.copiedEmail)).includes('@'));
 await page.evaluate(()=>navigator.clipboard.writeText=async()=>{throw Error('Clipboard denied')});await page.locator('.copy-mail:visible').first().click();assert((await page.locator('.sr-only[role=status]').textContent()).includes('selected'));assert.equal(await page.evaluate(()=>getSelection().toString()),await page.locator('.copy-mail:visible').first().getAttribute('data-copy'));
 const risky=await page.locator('a[target="_blank"]').evaluateAll(es=>es.filter(e=>!e.rel.includes('noopener')).map(e=>e.href));assert.deepEqual(risky,[]);
 await page.goto(base+'/404.html');assert.equal(await page.title(),'Page not found — Vasu-Devs');assert(await page.locator('a[href="/"]').first().isVisible());assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.equal(await page.locator('meta[name=robots]').getAttribute('content'),'noindex,follow');fs.mkdirSync(path.join(__dirname,'../.cache/details-qa'),{recursive:true});await page.screenshot({path:path.join(__dirname,'../.cache/details-qa/404-phone.png')});assert.deepEqual(errors,[]);console.log(JSON.stringify({manifestIcons:true,structuredData:true,crawlerFiles:true,keyboardSectionFocus:true,skipLinkPreservesSection:true,copyAnnouncement:true,externalLinkSafety:true,phone404:true,errors}));
}finally{await browser?.close();server.closeAllConnections();await new Promise(r=>server.close(r))}})().catch(e=>{console.error(e);process.exitCode=1});
