// Run after npm run build with Chromium and WebKit installed for Playwright.
const {createServer}=require('./serve-mobile-check.cjs');
const {chromium,webkit}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const out=path.join(__dirname,'../.cache/mobile-qa');fs.mkdirSync(out,{recursive:true});
(async()=>{const server=createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;const results=[];let browser;
try{for(const [name,engine]of [['chromium',chromium],['webkit',webkit]]){
 browser=await engine.launch();const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:2,reducedMotion:'reduce'});const errors=[],missing=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400&&r.url().startsWith(base))missing.push(r.url())});await page.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.abort());
 await page.addInitScript(()=>{window.audioStarts=0;const Native=window.AudioContext;if(Native)window.AudioContext=new Proxy(Native,{construct(T,args){const ctx=new T(...args),make=ctx.createBufferSource.bind(ctx);ctx.createBufferSource=()=>{const source=make(),start=source.start.bind(source);source.start=(...a)=>{window.audioStarts++;return start(...a)};return source};return ctx}})});
 await page.goto(base);await page.evaluate(()=>document.fonts.ready);const widths=[];
 for(const [width,height]of [[320,740],[360,800],[390,844],[430,932],[600,900],[844,390]]){
  await page.setViewportSize({width,height});
  for(const panel of ['home','projects','contact']){await page.locator('.navigation [data-page='+panel+']').tap();await page.locator('#'+panel).waitFor({state:'visible'});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`${name}: overflow ${panel} ${width}`);if(width===390)await page.screenshot({path:path.join(out,`${name}-${panel}.png`),fullPage:panel==='contact'})}
  if(width<=600||height<=500){const targets=await page.locator('.social-icon-row a,.navigation>a,.sound-toggle,.availability-badge,.contact-utilities a,.proj-actions a,.proj-actions button,.home-contact-links a,.tech').evaluateAll(es=>es.filter(e=>e.getClientRects().length).map(e=>({label:e.getAttribute('aria-label')||e.textContent.trim().slice(0,20),w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height})));assert(targets.every(t=>t.w>=43.9&&t.h>=43.9),JSON.stringify({name,width,viewport:await page.evaluate(()=>({w:innerWidth,h:innerHeight,coarse:matchMedia("(pointer:coarse)").matches})),small:targets.filter(t=>t.w<43.9||t.h<43.9)}))}
  await page.locator('.navigation [data-page=projects]').tap();await page.locator('#projects').waitFor({state:'visible'});await page.locator('button.proj-open').first().tap();const dialog=page.locator('.detail-modal[open]');await dialog.waitFor();
  if(width<=600||height<=500){const dimensions=await dialog.evaluate(d=>{const body=d.querySelector('.resume-content');body.scrollTop=body.scrollHeight;const close=d.querySelector('[aria-label="Close details"]').getBoundingClientRect();return{w:d.getBoundingClientRect().width,h:d.getBoundingClientRect().height,scroll:body.scrollTop,overflow:body.scrollWidth>body.clientWidth+1,closeTop:close.top,closeBottom:close.bottom}});assert(dimensions.w<=width&&dimensions.h<=height&&dimensions.scroll>0&&!dimensions.overflow&&dimensions.closeTop>=0&&dimensions.closeBottom<=height,JSON.stringify({name,width,dimensions}))}
  if(width===390){await dialog.locator('.resume-content').evaluate(e=>e.scrollTop=0);await page.screenshot({path:path.join(out,`${name}-dialog.png`)})}
  await page.locator('[aria-label="Close details"]').tap();assert.equal(await page.locator('dialog[open]').count(),0);widths.push(width);
 }
 await page.setViewportSize({width:390,height:844});await page.locator('.navigation [data-page=home]').tap();await page.locator('#home').waitFor({state:'visible'});await page.locator('.github-activity').scrollIntoViewIfNeeded();
 const graph=page.locator('.graph-scroll');assert(await graph.evaluate(e=>e.scrollWidth>e.clientWidth&&e.scrollLeft>0));const last=await page.locator('.graph-readout-text').innerText();await page.getByRole('button',{name:'Previous contribution day',exact:true}).tap();assert.notEqual(await page.locator('.graph-readout-text').innerText(),last);await page.getByRole('button',{name:'Next contribution day',exact:true}).tap();assert.equal(await page.locator('.graph-readout-text').innerText(),last);
 await page.screenshot({path:path.join(out,`${name}-graph.png`)});
 const swipe=async()=>{if(name==='chromium'){
  await page.locator('.github-activity').scrollIntoViewIfNeeded();await graph.evaluate(e=>e.scrollLeft=e.scrollWidth);
  const session=await page.context().newCDPSession(page);const r=await graph.boundingBox();await page.waitForTimeout(200);const before=await page.evaluate(()=>({audio:audioStarts,left:document.querySelector('.graph-scroll').scrollLeft,label:document.querySelector('.graph-readout-text').textContent}));
  const y=r.y+55,x=r.x+35;await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});for(let i=1;i<=8;i++){await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+i*25,y}]});await page.waitForTimeout(16)}await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForTimeout(200);
  const after=await page.evaluate(()=>({audio:audioStarts,left:document.querySelector('.graph-scroll').scrollLeft,label:document.querySelector('.graph-readout-text').textContent}));assert(after.left<before.left-80,'Calendar did not swipe');assert.equal(after.audio,before.audio,'Swipe emitted audio');assert.equal(after.label,before.label,'Swipe changed selected day');await session.detach();
 }};
 await page.evaluate(()=>scrollTo(0,0));await page.locator('.contact-utilities a[href="/resume.html"]').tap();await page.locator('.resume-modal[open]').waitFor();await page.locator('[data-resume-close]').tap();await page.locator('[data-open-contact]').tap();await page.locator('.contact-dialog[open]').waitFor();await page.locator('[data-close-contact]').tap();
 const audioSupported=await page.evaluate(()=>!!(window.AudioContext||window.webkitAudioContext));
 if(audioSupported){if(await page.locator('.sound-toggle').getAttribute('aria-pressed')!=='true')await page.locator('.sound-toggle').tap();await page.waitForFunction(()=>document.querySelector('.sound-toggle').getAttribute('aria-pressed')==='true');await page.locator('.sound-toggle').tap();await page.reload();assert.equal(await page.locator('.sound-toggle').getAttribute('aria-pressed'),'false')}
  else{assert.equal(await page.locator('.sound-toggle').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('.sound-toggle').getAttribute('data-audio-state'),'inactive')}
 await swipe();assert.deepEqual(errors,[]);assert.deepEqual(missing,[]);results.push({engine:name,widths,touchTargets:true,dialogsScroll:true,calendarControls:true,swipeNoSounds:name==='chromium'?true:'tested in Chromium',mutePersists:audioSupported?true:'Web Audio unavailable in this test engine',errors,missing});await browser.close();browser=null;
}fs.writeFileSync(path.join(out,'qa.json'),JSON.stringify(results,null,2));console.log(JSON.stringify(results));
}finally{await browser?.close();server.closeAllConnections();await new Promise(r=>server.close(r))}})().catch(e=>{console.error(e);process.exitCode=1});
